# Profile information
name: Hugo Koji Tamaki
title: Hugo Koji Tamaki
description:
  Hugo Koji Tamaki, desenvolvedor Ruby, JavaScript e gamer.
permalink: ':title/'
url: "hugotamaki.github.io"

# Social
facebook: hugo.tamaki
github: hugotamaki

# Contact form
email: #your-email@domain.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages, _posts]
sass:
  compress: true

social:
  name: Hugo Koji Tamaki
  links:
    - https://www.facebook.com/hugo.tamaki
    - https://github.com/HugoTamaki
